Console.ForegroundColor = ConsoleColor.Red;
Console.WriteLine("AÇAI - DJAVAN");
Console.ResetColor();
Console.WriteLine("");
Console.WriteLine("Solidão de manhã\nPoeira tomando assento\nRajada de vento\nSom de assombração, coração\nSangrando toda palavra sã");
Console.ResetColor();
Console.WriteLine("");
Console.ForegroundColor = ConsoleColor.Green;
Console.WriteLine("A paixão, puro afã\nMístico clã de sereia\nCastelo de areia\nIra de tubarão, ilusão\nO Sol brilha por si");
Console.ResetColor();
Console.WriteLine("");
Console.ForegroundColor = ConsoleColor.Blue;
Console.WriteLine("Açaí guardiã\nZum de besouro, um ímã\nBranca é a tez da manhã\nAçaí guardiã\nZum de besouro, um ímã\nBranca é a tez da manhã\n");
Console.WriteLine("");
Console.WriteLine("Açaí guardiã\nZum de besouro, um ímã\nBranca é a tez da manhã\nAçaí guardiã\nZum de besouro, um ímã\nBranca é a tez da manhã\n");
Console.ResetColor();
Console.WriteLine("");
Console.ForegroundColor = ConsoleColor.Yellow;
Console.WriteLine("Solidão de manhã\nPoeira tomando assento\nRajada de vento\nSom de assombração, coração\nSangrando toda palavra sã");
Console.ResetColor();
Console.WriteLine("");
Console.ForegroundColor = ConsoleColor.Magenta;
Console.WriteLine("La passion, puro afã\nMístico clã de sereia\nCastelo de areia\nIra de tubarão, iIlusão\nO Sol brilha por si");
Console.ResetColor();
Console.WriteLine("");
Console.ForegroundColor = ConsoleColor.Blue;
Console.WriteLine("Açaí guardiã\nZum de besouro, um ímã\nBranca é a tez da manhã\nAçaí guardiã\nZum de besouro, um ímã\nBranca é a tez da manhã\n");
Console.WriteLine("");
Console.WriteLine("Açaí guardiã\nZum de besouro, um ímã\nBranca é a tez da manhã\nAçaí guardiã\nZum de besouro, um ímã\nBranca é a tez da manhã\n");
